version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"   
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000/api/data

  logger:
    build: ./logger
    container_name: logger
    depends_on:
      - backend
      - frontend

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
