name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Run tests
        run: echo "No tests yet"

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend
        working-directory: ./backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/assignment:backend -f Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/assignment:backend

      - name: Build & Push Frontend
        working-directory: ./frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/assignment:frontend -f Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/assignment:frontend

      - name: Build & Push Logger
        working-directory: ./logger
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/assignment:logger -f Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/assignment:logger

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: failure()
    steps:
      - name: Send Failure Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: GitHub Actions Workflow Failed
          to: shashank.kanade@sdbi.in
          from: ${{ secrets.GMAIL_USERNAME }}
          body: |
            The CI/CD pipeline has failed.  
            Please check the Actions tab in the repository for details.
